try {
  //LOGICA
} catch (error) {
  //ERROR
}

try {
  //LOGICA
} catch {
  //ERROR
  console.log();
}